Patch 1 seis AI asset update
Sei-Public-Goods/sei-assetlist pull request #23
Opened 2024-11-10 04:51 UTC by seisaicoin

2024-11-10 04:52 UTC, seisaicoin reviewed
Am hoping it's right now and will update.

2024-11-10 05:10 UTC, seisaicoin reviewed
Asset addition request: forked, cloned and updated with a correct logo url for seis AI

2024-12-02 18:38 UTC, Cordtus requested changes

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
>  }
invalid json, add a comma here

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +}
and here

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +
remove this empty line

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +  "type_asset": "sdk.coin"
this is incorrect for an erc20 token

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +    "png": "https://raw.githubusercontent.com/seisaicoin/SEIS/refs/heads/main/seis%20AI%20token%20logo.png"
please add the image to this repo and link it from there

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +    "png": "https://raw.githubusercontent.com/seisaicoin/SEIS/refs/heads/main/seis%20AI%20token%20logo.png"
same as above

2024-12-02 18:38 UTC, Cordtus commented on assetlist.json
> +  "type_asset": "sdk.coin"
same as above

2025-01-23 21:31 UTC, closed without merging

2025-01-24 02:11 UTC, seisaicoin commented
dev said he did this, and i didn't see where either. can attempt to try again, and asking max to help, as don't want error and he was so kind to comment in detail.